@startuml

object House{
mID
}

object Address {
mStreet
mZipCode
mTown
}

object GeographicalArea{
mID
mDesignation
}

object Location{
mLatitude
mLongitude
mAltitude
}

object TypeGA


object OccupationArea{
mLength
mWidth
}


object Room{
mName
mFloor
mHeight
}


object Sensor{
mDesignation
mStartDate
mUnit
}

object SensorType

object HouseGrid {
mDesignation
mContractedMaximumPower
}

object Reading{
mValue
mDateAndTime
}

object Device {
mName
mNominalPower
}

object DeviceType

object PowerSource{
mName
mTypePS
mMaxPower
mStorageCapacity
}



House -- "1" GeographicalArea: belongs to
House -- "1" Address: has
House *-- "*" Room: contains
House o-- "*" HouseGrid: contains

Address "1" -- "1" Location: has

GeographicalArea ->  GeographicalArea: is in 0..1
GeographicalArea "1..*"-- "1" TypeGA: has
GeographicalArea" 1" o-- "1..*" Sensor
GeographicalArea "   1"-- "1" OccupationArea: has
GeographicalArea "1..*  "-- "1" Location: has

Room "1" o-- "          *"Sensor: contains
Room "1"*-- "1..*"Device: contains
Room "0..*"-- "1" HouseGrid: belongs to
Room "1"-- "1" OccupationArea: has


Sensor *-- "1..*"Reading: contains
Sensor "*" --* "1" SensorType: has
Sensor "1" -- "1" Location: is in

HouseGrid "1" o--  "*" PowerSource: has

Device "1..*" --* "1" DeviceType: has
@enduml