@startuml
skinparam linetype polyline

object House{
mID
}

object Address {
mStreet
mZipCode
mTown
}

object GeographicalArea{
mID
mDesignation
}

object Location{
mLatitude
mLongitude
mAltitude
}

object TypeGA


object OccupationArea{

mLength
mWidth
}


object Room{
mName
mFloor
mArea
mHeight
}


object Sensor{
mDesignation
mStartDate
mUnit
}

object SensorType

object HouseGrid {
mDesignation
mContractedMaximumPower
}

object Reading{
mValue
mDateAndTime
}

object Device {
mName
mDeviceSpecs
mNominalPower
mActive
mIsMetered
}

object DeviceType

object PowerSource{
mName
mTypePS
mMaxPower
mStorageCapacity
}

object Program{
mName
mEnergyConsumption
}

House -- "1" GeographicalArea: > belongs to
House -- "1" Address: has >
House -- "1..*" HouseGrid: contains
HouseGrid --  "1..*" Room: has attached
House --"*" Room: contains

Address "1" -- "1   " Location: has

GeographicalArea ->  GeographicalArea: is in 0..1
GeographicalArea "1..*"-- "1" TypeGA: has
GeographicalArea"   1" -- "1..* " Sensor
GeographicalArea "   1"-- "    1" OccupationArea: has
GeographicalArea "1..*  "-- "1" Location: has

Room "1 " -- "*" Sensor: contains
Room "1" -- "1..*  "Device: contains
Room "1"-- "1" OccupationArea: has


Sensor -- "1..*  "Reading: contains
Sensor "*" -- "1" SensorType: has
Sensor "1" -- "1" Location: > is in

HouseGrid "1" --  "*" PowerSource: has

Device "1..*" -- "1" DeviceType: has
Device -- "0..*  "Reading: > contains
Device "1" -- "0..*" Program: has





@enduml