@startuml
skinparam linetype ortho
hide empty members

skinparam class {
	ArrowColor SteelBlue
	BorderColor Dimgray
	HeaderBackgroundColor SteelBlue
	BackgroundColor White
	FontName Calibri bold
	AttributeFontColor #333
	AttributeFontName Calibri
	AttributeFontSize 13
	FontColor Ivory
	FontSize 15
}

class RoomCTRL{
- RoomService
+ updateOne()
}

class RoomService{
- RoomRepository
- RoomMapper

+ findById()
+ save()
}

class RoomMapper {
+ toDetailDto()
+ toObject()
}

Interface RoomRepository{

+ findById()
+ save()

}

class Room{
- id
- description
- floor
- length
- width
- height

+ setFloor()
+ setLength()
+ setWidth()
+ seHeight()
}

class RoomDetailDTO{
- id
- description
- floor
- length
- width
- height

+ setFloor()
+ setLength()
+ setWidth()
+ seHeight()

}

RoomCTRL --> RoomService
RoomCTRL -> ResponseEntity
RoomService -> RoomMapper
RoomService -> Room
RoomMapper -> RoomDetailDTO
RoomMapper --> Room
RoomService --> RoomRepository
RoomRepository -> Room


@enduml