@startuml
autonumber
hidefootbox


skinparam sequence {
	ArrowColor SteelBlue
	ActorBorderColor Dimgray
	LifeLineBorderColor MidnightBlue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Dimgray
	ParticipantBackgroundColor SteelBlue
	ParticipantFontName Calibri Bold
	ParticipantFontSize 17
	ParticipantFontColor Ivory

	ActorBackgroundColor SteelBlue
	ActorFontColor MidnightBlue
	ActorFontSize 17
	ActorFontName Aapex

}

skinparam note {
BorderColor SteelBlue
}

'START FROM CONTROLLER


":ConfigureHouseCTRL"->":DataImport": importHouseConfiguration(path)

":DataImport" -> ":{FileReaderHouse}":create()

create "ad:Address"

":{FileReaderHouse}" -> "ad:Address":importAddress()
":{FileReaderHouse}" -> "ad:Address":create()
":{FileReaderHouse}" -> "ad:Address":setAddress(ad)

loop Import of the list of Rooms
create "r:Room"
":{FileReaderHouse}" -> "r:Room":importRooms()
":{FileReaderHouse}" -> "r:Room":create()
":{FileReaderHouse}" -> ":RoomList":addRoom(r)
end

loop
create "hg:HouseGrid"
":{FileReaderHouse}" -> "hg:HouseGrid":importGrids()
":{FileReaderHouse}" -> "hg:HouseGrid":create()
":{FileReaderHouse}" -> ":HouseGridList":addHouseGrid()

end



@enduml