@startuml
hidefootbox
actor Admin

create ":DeactivateSensorUI"
Admin -> ":DeactivateSensorUI":  Deactivate sensor in \nGeographical Area
create ":DeactivateSensorCTRL"
":DeactivateSensorUI" -> ":DeactivateSensorCTRL": create(gaList)

":DeactivateSensorUI" -> ":DeactivateSensorCTRL": listGADto=getGAList()

create ":GeographicalAreaMapper"
":DeactivateSensorCTRL"->":GeographicalAreaMapper":create()
":DeactivateSensorCTRL"->":GeographicalAreaMapper":listGaDTO=toDtoList(ga)
":GeographicalAreaMapper" -> "gaList:GAList": gaList=getGAList

loop for each ga in gaList convert toDTO
create "gaDTO: daDto"
":GeographicalAreaMapper"->"gaDTO: daDto":create()
":GeographicalAreaMapper"->":GeographicalAreaMapper":add(gaDTO)
end

Admin <-- ":DeactivateSensorUI": Show Geographical Areas
Admin -> ":DeactivateSensorUI": Choose Geographical Area


":DeactivateSensorUI" -> ":DeactivateSensorCTRL": listSDto=getSensorIfActiveToDto()
loop for each ga in gaList match id
":DeactivateSensorCTRL"->"gaList:GAList": ga=getGAById(gaDTOId)
end

":DeactivateSensorCTRL"->"ga:GeographicalArea":sL=getSensorListInGA(ga)

loop for each active Sensor in the GA SensorList convert toDTO
":DeactivateSensorCTRL" -> "sL:SensorList":s=getActiveSensors
create ":SensorMapper"
":DeactivateSensorCTRL"->":SensorMapper":create()
":DeactivateSensorCTRL"->":SensorMapper":toDto(s)
create "sDTO:sensorDTO"
":SensorMapper"->"sDTO:sensorDTO":create()
":DeactivateSensorCTRL" -> ":DeactivateSensorCTRL":add (sDTO)
end

Admin <-- ":DeactivateSensorUI": Show Sensors in\n Geographical Area
Admin -> ":DeactivateSensorUI": Choose Sensor

":DeactivateSensorUI" -> ":DeactivateSensorUI":sensorDTO=listSDto.get(index)
":DeactivateSensorUI" -> ":DeactivateSensorUI":sensorDTOId=sensorDTO.getId()

Admin <-- ":DeactivateSensorUI": Ask for deactivation date
Admin -> ":DeactivateSensorUI": Insert deactivation date

":DeactivateSensorUI" -> ":DeactivateSensorCTRL":deactivateSensor(gaDTOId,sensorDTOId,date)

loop for each GA in gaList match DTO id
":DeactivateSensorCTRL"->"gaList:GAList": ga=getGAById(gaDTOId)
end
":DeactivateSensorCTRL"->"sL:SensorList": sL=getSensorListInGA()
loop for each active sensor in GA sensorList match id
":DeactivateSensorCTRL"->"sL:SensorList": s=s.getId().matches(sensorDTOId)
end
":DeactivateSensorCTRL"->"s:Sensor":deactivate

Admin <-- ":DeactivateSensorUI": Show Deactivation Message

@enduml