@startuml
hidefootbox


actor Administrator
":EditDeviceUI" -> ":EditDeviceCTRL": dL=getListDevices(Room r)
":EditDeviceCTRL" -> ":House": dL=getListDevices(Room r)
":House" -> "rL:RoomList": dL=getListDevices(Room r)
"rL:RoomList" -> "r:Room": dL=r.getListDevices()
"r:Room" -> "dL:DeviceList": dL=r.getListDevices()


@enduml