@startuml
hidefootbox

actor Administrator
":EditDeviceUI" -> ":EditDeviceCTRL": aL=getDeviceAttributesList(Device d)
":EditDeviceCTRL" -> ":House": aL=getDeviceAttributesList(Device d)
":House" -> "rL:RoomList": aL=getDeviceAttributesList(Device d)
"rL:RoomList" -> ":Room": aL=getDeviceAttributesList(Device d)
":Room" -> "dL:DeviceList": aL=getDeviceAttributesList(Device d)
"dL:DeviceList" -> "d:Device": aL=getDeviceAttributesList()
"d:Device" -> "DeviceSpecs": aL=getDeviceAttributesList()


@enduml