@startuml
autonumber
hidefootbox
actor Administrator


Administrator -> ":DataImportUI": Ask import
create ":DataImportCTRL"


":DataImportUI" -> ":DataImportCTRL": create
":DataImportUI" -> "Administrator": ask for file name and path
":DataImportUI" <- "Administrator": type  file name and path


":DataImportUI" -> ":DataImportCTRL": importData\nFromCSVFile(filePath)
":DataImportCTRL" -> ":GAList": importDataFromCSV\nFileForEachGA(filePath)

loop for each Geographical Area in GAList
":GAList" -> ":GeographicalArea": importReadingsToSensors\nFromCSVFile(filePath)


create ":ReadCSVFile"
":GeographicalArea" -> ":ReadCSVFile": create
":GeographicalArea" -> ":ReadCSVFile": readCSVFile(filePath)
":ReadCSVFile" -> ":GeographicalArea": getDataFromCSVFile()

":GeographicalArea" -> ":SensorList": getSensorListinGA()

loop for each sensor in SensorList
":SensorList" -> ":Sensor": get()

":Sensor" -> ":ReadingList": getReadingList()
create "r:Reading"

":ReadingList" -> "r:Reading": newReading(date,value)
":ReadingList" <- ":ReadingList": addReading(r)
end
end
":DataImportCTRL"<-":DataImportUI":gaListDTO=showGAsDTOs
loop for each GA in gL convert to DTO
":DataImportCTRL"->":GeographicalArea": toDTO()
create "gaDTO:GeographicalAreaDTO"
"ga:GeographicalArea"->"gaDTO:GeographicalAreaDTO": gaDTO=create()
":DataImportCTRL"->"gaDTO:GeographicalAreaDTO": add(gaDTO)
end
":DataImportCTRL"->":DataImportCTRL": gaListDTO=getGAListDTO()

Administrator<--":DataImportUI": Shows the number \nof readings of each sensor
@enduml