@startuml
autonumber
hidefootbox

actor SysAdmin

create ":DataImportUI"
SysAdmin -> ":DataImportUI": Import GAs and \nSensors from a File

create ":DataImportCTRL"
":DataImportUI" -> ":DataImportCTRL": create(gL)
SysAdmin <-- ":DataImportUI": Request file path
SysAdmin -> ":DataImportUI": Enters file path
":DataImportUI" -> ":DataImportCTRL": loadFile(filepath)

create ":{Reader}"
":DataImportCTRL"->":{Reader}": create(filePath,gL)
note right
{Reader} can be:
    XMLReader
    JSONReader
end note

":DataImportCTRL" -> ":{Reader}": importGAs( )
":{Reader}" -> "gL:GAList": importGAsFromFile( )


loop Import Geographical Areas from file

create "ga:GeographicalArea"
"gL:GAList" -> "ga:GeographicalArea": ga = newGAFromFile()


create "sL:SensorList"
"ga:GeographicalArea" -> "sL:SensorList": create( )


"gL:GAList"->"gL:GAList": add(GA)
end

":DataImportCTRL" -> ":{Reader}": importSensors( )
":{Reader}" -> "sL:SensorList": importSensorsFromFile( )

loop import sensors from file

create "s:Sensor"
"sL:SensorList"->"s:Sensor":s = newSensorFromFile()
"sL:SensorList"->"sL:SensorList": addGASensor(s)
end


":DataImportCTRL"<-":DataImportUI":gaListDTO=\nshowGAsDTOs( )

loop for each geographical area in gL convert to DTO
":DataImportCTRL"->"ga:GeographicalArea": toDTO( )

create "gaDTO:GeographicalAreaDTO"
"ga:GeographicalArea"->"gaDTO:GeographicalAreaDTO": gaDTO=create()
":DataImportCTRL"->"gaDTO:GeographicalAreaDTO": add(gaDTO)

end

":DataImportCTRL"->":DataImportCTRL": gaListDTO=getGAListDTO()
SysAdmin<--":DataImportUI": Show message with number\nof Geographical Areas and\nSensors successfully imported
@enduml