@startuml
 autonumber
 hidefootbox
 actor User

User -> SmartHomeUI: main()
SmartHomeUI ->SmartHomeUI: setUp()
SmartHomeUI <- SmartHomeUI: showUserRoles()
User <-- SmartHomeUI: Show Users Role
User -> SmartHomeUI: Choose User Role

create ":{userRole}UI"
SmartHomeUI -> ":{userRole}UI": create()
note right
	{userRole} can be:
	 System Administration
	 House Administration
	 Regular User
	 Power User
	 Room Owner
end note

SmartHomeUI -> ":{userRole}UI": run()
":{userRole}UI" -> ":{userRole}UI": showOptions()
User <-- ":{userRole}UI": Show Options
User -> ":{userRole}UI": Select Option
create ":{option}UI"
":{userRole}UI" -> ":{option}UI": create(...)
note right
	{option} dependents on the User Story
end note
":{userRole}UI" -> ":{option}UI": run()
create ":{option}CTRL"
":{option}UI" -> ":{option}CTRL": create(...)






@enduml