@startuml
autonumber
hidefootbox

actor Administrator
participant ":EditDeviceUI" order 1
participant ":EditDeviceCTRL" order 2
participant ":House" order 3
participant "rL:RoomList" order 4
participant "r:Room" order 5
participant "dL:DeviceList" order 6

Administrator -> ":EditDeviceUI": Remove Device

activate ":EditDeviceUI"
":EditDeviceUI" -> ":EditDeviceCTRL": rList = showRoomListInString( )

activate ":EditDeviceCTRL"
":EditDeviceCTRL" -> ":House": rList = showRoomListInString( )

activate ":House"
":House" -> "rL:RoomList": rList = showRoomListInString( )
activate "rL:RoomList"
deactivate "rL:RoomList"
deactivate ":House"

Administrator <<-- ":EditDeviceUI": Show list of Rooms
Administrator -> ":EditDeviceUI": Choose Room

'":EditDeviceCTRL" -> "r:Room": dL = getDeviceList( )
":EditDeviceUI" -> ":EditDeviceCTRL": dList = showDeviceListInString( )
":EditDeviceCTRL" -> "dL:DeviceList": dList = showDeviceListInString( )
activate "dL:DeviceList"
deactivate "dL:DeviceList"

Administrator <<-- ":EditDeviceUI": Show device list

Administrator -> ":EditDeviceUI": Choose device

":EditDeviceUI" -> ":EditDeviceCTRL": removeDevice(roomIndex, deviceIndex)
":EditDeviceCTRL" -> "rL:RoomList": removeDevice(roomIndex, deviceIndex)
"rL:RoomList" -> "r:Room": remove(deviceIndex)
"r:Room" -> "dL:DeviceList": remove(device)

'device = room.getDeviceList().get(deviceIndex)
":EditDeviceUI" -> ":EditDeviceCTRL": dList = showDeviceListInString( )
":EditDeviceCTRL" -> "dL:DeviceList": dList = showDeviceListInString( )
deactivate ":EditDeviceCTRL"
activate "dL:DeviceList"
deactivate "dL:DeviceList"
deactivate "r:Room"
Administrator <<-- ":EditDeviceUI": Show updated device list
deactivate ":EditDeviceCTRL"

@enduml