@startuml
skinparam linetype ortho

skinparam object {
	ArrowColor SteelBlue
	BorderColor Dimgray
	BackgroundColor SteelBlue

	AttributeFontColor #FFF
	AttributeFontName Calibri
	AttributeFontSize 12
	AttributeBackgroundColor White

	FontColor Ivory
	FontSize 16
}

object House {
iD
}

object Address {
<color: White>
street
zipCode
town
}

object GeographicalArea{
iD
designation
}

object Location{
latitude
longitude
altitude
}

object TypeGA


object OccupationArea{
length
width
}


object Room{
name
floor
height
}


object Sensor{
iD
designation
startDate
unit
}

object SensorType

object HouseGrid {
designation
contractedMaximumPower
}

object Reading{
value
dateAndTime
}

object Device {
name
nominalPower
active
}

object DeviceType

object DeviceSpecs{
attributes
}

object PowerSource{
name
typePS
maxPower
storageCapacity
}

object Program{
name
value
}

House - "1" GeographicalArea
House -- "1" Address
House -"*" Room

House -- "1..*" HouseGrid
HouseGrid "1" -- "1..*" Room
HouseGrid "1" -- "*" PowerSource

Address "1" - "1   " Location

GeographicalArea"1" -> "1"GeographicalArea
GeographicalArea "1..*"-- "1" TypeGA
GeographicalArea"1" -- "1..* " Sensor
OccupationArea "1" - "1" GeographicalArea
GeographicalArea "1..*  "- "1" Location

Room "1 " -- "*" Sensor
Room "1" -- "1..*  "Device
Room "1"- "1" OccupationArea


Sensor -- "1..*  "Reading
Sensor "*" - "1" SensorType
Sensor "1" -- "1" Location


Device "1..*" -- "1" DeviceSpecs
Device "1..*" -- "1" DeviceType
Device "1" -- "0..*" Program
Device "1"-- "0..*"Reading


@enduml