@startuml
skinparam linetype polyline

object House{
iD
}

object Address {
street
zipCode
town
}

object GeographicalArea{
iD
designation
}

object Location{
latitude
longitude
altitude
}

object TypeGA


object OccupationArea{
length
width
}


object Room{
name
floor
area
height
}


object Sensor{
iD
designation
startDate
unit
}

object SensorType

object HouseGrid {
designation
contractedMaximumPower
}

object Reading{
value
dateAndTime
}

object Device {
name
nominalPower
active
}

object DeviceType

object DeviceSpecs{
attributes
}

object PowerSource{
name
typePS
maxPower
storageCapacity
}

object Program{
name
value
}

House -- "1" GeographicalArea: > belongs to
House -- "1" Address: has >
House -- "1..*" HouseGrid: contains
HouseGrid --  "1..*" Room: has attached
House --"*" Room: contains

Address "1" -- "1   " Location: has

GeographicalArea ->  GeographicalArea: is in 0..1
GeographicalArea "1..*"-- "1" TypeGA: has
GeographicalArea"   1" -- "1..* " Sensor
GeographicalArea "   1"-- "    1" OccupationArea: has
GeographicalArea "1..*  "-- "1" Location: has

Room "1 " -- "*" Sensor: contains
Room "1" -- "1..*  "Device: contains
Room "1"-- "1" OccupationArea: has


Sensor -- "1..*  "Reading: contains
Sensor "*" -- "1" SensorType: has
Sensor "1" -- "1" Location: > is in

HouseGrid "1" --  "*" PowerSource: has

Device "1..*" -- "1" DeviceType: has
Device "1..*" -- "1" DeviceSpecs: has
Device -- "0..*  "Reading: > contains
Device "1" -- "0..*" Program: has





@enduml