@startuml
autonumber
hidefootbox

actor Administrator
participant "rL:RoomList" order 4
participant "r:Room" order 5
participant "dL:DeviceList" order 6
participant "d:Device" order 7

Administrator -> ":EditDeviceUI": Deactivate Device


activate ":EditDeviceUI"
":EditDeviceUI" -> ":EditDeviceCTRL": rList = showRoomListInString( )

activate ":EditDeviceCTRL"
":EditDeviceCTRL" -> "rL:RoomList": rList = showRoomListInString( )
activate "rL:RoomList"
deactivate "rL:RoomList"
Administrator <<-- ":EditDeviceUI": Show room list

Administrator -> ":EditDeviceUI": Choose room
":EditDeviceUI" -> ":EditDeviceCTRL": dList = showDeviceListInString( )
":EditDeviceCTRL" -> "dL:DeviceList": dList = showDeviceListInString( )
activate "dL:DeviceList"
deactivate "dL:DeviceList"
Administrator <<-- ":EditDeviceUI": Show device list

Administrator -> ":EditDeviceUI": Choose device

":EditDeviceUI" -> ":EditDeviceCTRL": deactivateDevice(roomIndex, deviceIndex)

":EditDeviceCTRL" -> "rL:RoomList": deactivateDevice(roomIndex, deviceIndex)
activate "r:Room"
"r:Room" -> "dL:DeviceList": deactivateDevice(deviceIndex)
activate "dL:DeviceList"
"dL:DeviceList" -> "d:Device": deactivateDevice( )
activate "d:Device"
deactivate "d:Device"
":EditDeviceUI" -> ":EditDeviceCTRL": dList = showDeviceListInString( )
":EditDeviceCTRL" -> "dL:DeviceList": dList = showDeviceListInString( )
deactivate "dL:DeviceList"
deactivate "dL:DeviceList"
deactivate "r:Room"
deactivate ":EditDeviceCTRL"
Administrator <<-- ":EditDeviceUI": Show updated device list
deactivate ":EditDeviceUI"
@enduml