@startuml
autonumber
hidefootbox
actor Administrator


Administrator -> ":EditDeviceUI": Edit a device
create ":EditDeviceCTRL"

":EditDeviceUI" -->> ":EditDeviceCTRL": create

":EditDeviceUI" -> ":EditDeviceCTRL": rL=getRoomList()
":EditDeviceCTRL" -> ":House": rL=getRoomList()
":House"-> "rL:RoomList": rL=getRoomList()


Administrator <<-- ":EditDeviceUI": Show room list
Administrator -> ":EditDeviceUI": Choose room

ref over ":EditDeviceUI", ":EditDeviceCTRL", ":House", "rL:RoomList", ":Room", "dL:DeviceList": dL=r.getListDevices()



Administrator <<-- ":EditDeviceUI": Show device list
Administrator -> ":EditDeviceUI": Choose device

ref over ":EditDeviceUI", ":EditDeviceCTRL", ":House", "rL:RoomList", ":Room", "dL:DeviceList", ":Device", "DeviceSpecs": aL=getDeviceAttributesList()


Administrator <<-- ":EditDeviceUI": Show attribute list
Administrator -> ":EditDeviceUI": Choose attribute
":EditDeviceUI" -> ":EditDeviceUI": Input new value
Administrator -> ":EditDeviceUI": Insert value


ref over ":EditDeviceUI", ":EditDeviceCTRL", ":House", "rL:RoomList", ":Room", "dL:DeviceList", ":Device", "DeviceSpecs": setAttributeValue\n(device,attribute,value)


Administrator <<-- ":EditDeviceUI": Success message
@enduml