@startuml
autonumber
hidefootbox

actor Administrator


Administrator -> EditDeviceUI: Edit a device

create EditDeviceCTRL
control EditDeviceCTRL
EditDeviceUI -->> EditDeviceCTRL: create
EditDeviceUI -> EditDeviceCTRL: rL=getRoomList()
EditDeviceCTRL -> "rL:RoomList": rL=getRoomList()

Administrator <<-- EditDeviceUI: show room list
Administrator -> EditDeviceUI: choose room

EditDeviceUI -> EditDeviceCTRL: dL=getListDevices(index)
EditDeviceCTRL -> "dL:DeviceList": dL=getListDevices(index)

Administrator <<-- EditDeviceUI: show device list
Administrator -> EditDeviceUI: choose device

EditDeviceUI -> EditDeviceCTRL: aL=getAttributeNames()
EditDeviceCTRL -> Device: aL=getAttributeNames()

Device -> DeviceSpecs: aL=getAttributeNames()

Administrator <<-- EditDeviceUI: show attribute list
Administrator -> EditDeviceUI: choose attribute

EditDeviceUI ->EditDeviceUI: input new value

Administrator -> EditDeviceUI: insert value

EditDeviceUI -> EditDeviceCTRL: changeAttValue(attribute,value)
EditDeviceCTRL -> Device: changeAttValue(attribute,value)

Device -> DeviceSpecs: setAttValue(attribute,value)

@enduml