@startuml
autonumber
hidefootbox


"EnergyConsumptionOfWaterHeating:UI" -> ":Controller": setColdWaterTemperature\nInEWHList\n(coldWaterTemperature)
":Controller" -> ":House": setColdWaterTemperature\nInEWHList\n(coldWaterTemperature)
":House"->":RoomList": setColdWaterTemperature\nInEWHList\n(coldWaterTemperature)
":RoomList" -> ":Room": setColdWaterTemperature\nInEWHList\n(coldWaterTemperature)
":Room" -> ":DeviceList": setColdWaterTemperature\nInEWHList\n(coldWaterTemperature)
":DeviceList" -> ":Device": setColdWaterTemperature\nInEWHList\n(coldWaterTemperature)

@enduml