@startuml
autonumber
hidefootbox

actor "Regular User/Power User"

"EnergyConsumptionOfWaterHeating:UI" -> ":Controller": h.setVolumeOfWaterInEWHList(volumeOfWater)
":Controller" -> ":House": h.setVolumeOfWaterInEWHList(volumeOfWater)
":House"->":RoomList": h.setVolumeOfWaterInEWHList(volumeOfWater)
":RoomList" -> ":Room": h.setVolumeOfWaterInEWHList(volumeOfWater)
":Room" -> ":DeviceList": h.setVolumeOfWaterInEWHList(volumeOfWater)
":DeviceList" -> ":Device": h.setVolumeOfWaterInEWHList(volumeOfWater)

@enduml