@startuml
autonumber
hidefootbox

"EnergyConsumptionOfWaterHeating:UI" -> ":Controller": setVolumeOfWater\nInEWHList (volumeOfWater)
":Controller" -> ":House": setVolumeOfWater\nInEWHList (volumeOfWater)
":House"->":RoomList": setVolumeOfWater\nInEWHList (volumeOfWater)
":RoomList" -> ":Room": setVolumeOfWater\nInEWHList (volumeOfWater)
":Room" -> ":DeviceList": setVolumeOfWater\nInEWHList (volumeOfWater)
":DeviceList" -> ":Device": setVolumeOfWater\nInEWHList (volumeOfWater)

@enduml