@startuml
autonumber
hidefootbox


"EnergyConsumptionOfWaterHeating:UI" -> ":Controller": h.getEnergyConsumption\nInEWHList( ): double
":Controller" -> "h:House": h.getEnergyConsumption\nInEWHList( ): double
"h:House"->":RoomList": h.getEnergyConsumption\nInEWHList( ): double
":RoomList" -> ":Room": h.getEnergyConsumption\nInEWHList( ): double
":Room" -> ":DeviceList": h.getEnergyConsumption\nInEWHList( ): double
":DeviceList" -> ":Device": h.getEnergyConsumption\nInEWHList( ): double

":Device" -->> ":DeviceList": energy consumption\nestimated value
":DeviceList" -->> ":Room": energy consumption\nestimated value
":Room" -->> ":RoomList": energy consumption\nestimated value
":RoomList" -->> "h:House": energy consumption\nestimated value
"h:House" -->> ":Controller": energy consumption\nestimated value
":Controller" -->> "EnergyConsumptionOfWaterHeating:UI": energy consumption\nestimated value
@enduml