@startuml
autonumber
hidefootbox

"EnergyConsumptionOfWaterHeating:UI" -> ":Controller": h.setVolumeOfWater\nInEWHList (volumeOfWater)
":Controller" -> ":House": h.setVolumeOfWater\nInEWHList (volumeOfWater)
":House"->":RoomList": h.setVolumeOfWater\nInEWHList (volumeOfWater)
":RoomList" -> ":Room": h.setVolumeOfWater\nInEWHList (volumeOfWater)
":Room" -> ":DeviceList": h.setVolumeOfWater\nInEWHList (volumeOfWater)
":DeviceList" -> ":Device": h.setVolumeOfWater\nInEWHList (volumeOfWater)

@enduml