@startuml
 autonumber
 hidefootbox
 actor Administrator


 Activate Administrator
 Administrator <-- ":MainUI" : Show menu
 Activate ":MainUI"
 Administrator -> ":MainUI": Chooses Power User menu
 Deactivate ":MainUI"
 create ":PowerUserUI"
 ":MainUI" ->":PowerUserUI": create
 Administrator <-- ":PowerUserUI": Show menu
 Activate ":PowerUserUI"
 Administrator->":PowerUserUI": chooses Energy Consumption in period of a device, room or grid
 Deactivate ":PowerUserUI"
 create ":EnergyConsumptionInPeriodUI"
 ":PowerUserUI"->":EnergyConsumptionInPeriodUI": create()
 create ":EnergyConsumptionInPeriodCTRL"
  ":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": create()

 Administrator <-- ":EnergyConsumptionInPeriodUI": Shows options: Device,Room and Grid
 Activate ":EnergyConsumptionInPeriodUI"
 Administrator -> ":EnergyConsumptionInPeriodUI": Selects Grid option

 ":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": hL = getHouseGridList()
 Activate ":EnergyConsumptionInPeriodCTRL"
 ":EnergyConsumptionInPeriodCTRL" -> "hL:HouseGridList": hL = getHouseGridList()
 Activate "hL:HouseGridList"
 ":EnergyConsumptionInPeriodCTRL"<--"hL:HouseGridList":showHouseGridList()
 Deactivate "hL:HouseGridList"
 ":EnergyConsumptionInPeriodUI"<--":EnergyConsumptionInPeriodCTRL":showHouseGridList()
  Deactivate ":EnergyConsumptionInPeriodCTRL"
 Administrator <-- ":EnergyConsumptionInPeriodUI": showHouseGridList()
 Administrator -> ":EnergyConsumptionInPeriodUI": Selects a HouseGrid
 Administrator <-- ":EnergyConsumptionInPeriodUI": Asks for the time interval
 Administrator -> ":EnergyConsumptionInPeriodUI": Inputs the time interval
 ":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": tMe = getEnergyConsumption\nInPeriod(index, start, end)
  Activate ":EnergyConsumptionInPeriodCTRL"

 ":EnergyConsumptionInPeriodCTRL" -> ":HouseGrid": tMe = getEnergyConsumption\nInPeriod(index, start, end)
 Activate  ":HouseGrid"
 ":EnergyConsumptionInPeriodCTRL" <-- ":HouseGrid": shows Grid EnergyConsumption
 Deactivate  ":HouseGrid"
 ":EnergyConsumptionInPeriodUI" <-- ":EnergyConsumptionInPeriodCTRL": shows Grid EnergyConsumption
 Deactivate  ":EnergyConsumptionInPeriodCTRL"
 Administrator <-- ":EnergyConsumptionInPeriodUI" : shows Grid EnergyConsumption in period
 Deactivate  ":EnergyConsumptionInPeriodUI"
 Deactivate Administrator
 @enduml