@startuml
autonumber
hidefootbox
actor PowerUser

activate PowerUser
create ":EnergyConsumptionInPeriodUI"
PowerUser -> ":EnergyConsumptionInPeriodUI": Get Total Metered\nEnergy Consumption
activate  ":EnergyConsumptionInPeriodUI"
PowerUser <-- ":EnergyConsumptionInPeriodUI": Show Options: Device,Room,Grid
PowerUser -> ":EnergyConsumptionInPeriodUI": Choose Grid option
create ":EnergyConsumptionInPeriodCTRL"
":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": create()
":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": gL=showHouseGridListInString()
activate ":EnergyConsumptionInPeriodCTRL"
":EnergyConsumptionInPeriodCTRL" -> "gL:HouseGridList": gL=showHouseGridListInString()
activate "gL:HouseGridList"
deactivate "gL:HouseGridList"
PowerUser <-- ":EnergyConsumptionInPeriodUI": Show Grid list
PowerUser -> ":EnergyConsumptionInPeriodUI": Choose a Grid
PowerUser <-- ":EnergyConsumptionInPeriodUI": Ask for the time interval
PowerUser -> ":EnergyConsumptionInPeriodUI": Input the time interval
":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": tMe=getEnergyConsumption\nInPeriod(index, start, end)
":EnergyConsumptionInPeriodCTRL" -> ":Grid": tMe=getEnergyConsumption\nInPeriod(index, start, end)
activate ":Grid"
":Grid" -> ":Device": tMe = getEnergyConsumption\nInPeriod(start, end)
activate ":Device"
":Device" -> "i:ReadConfigFile": i:getDevicesMeteringPeriod()
activate "i:ReadConfigFile"
deactivate "i:ReadConfigFile"
":Device" -> ":ReadingList": tMe=getValueOfReadings\nInTimeInterval(start, end)
activate ":ReadingList"
":ReadingList" -> "r:Reading": r=returnValueOfReading
activate "r:Reading"
deactivate "r:Reading"
deactivate ":ReadingList"
deactivate ":Device"
PowerUser <-- ":EnergyConsumptionInPeriodUI": Show Total Metered Energy\nConsumption in the Grid
deactivate ":Grid"
deactivate ":EnergyConsumptionInPeriodCTRL"
deactivate ":EnergyConsumptionInPeriodUI"


@enduml
