@startuml
autonumber
hidefootbox

actor Administrator

Administrator -> ":EditDeviceUI": start

create ":EditDeviceCTRL"
activate ":EditDeviceUI"
":EditDeviceUI" -> ":EditDeviceCTRL": create

activate ":EditDeviceCTRL"
":EditDeviceCTRL" -> ":House": rL = getRoomList( )

":House" -> "rL:RoomList": getRoomList( )

Administrator <<-- ":EditDeviceUI": Show room list

Administrator -> ":EditDeviceUI": Choose room

"rL:RoomList" -> ":Room": dL = getDevicesList( )

":Room" -> "dL :DeviceList": getDevicesList( )

Administrator <<-- ":EditDeviceUI": Show device list

Administrator -> ":EditDeviceUI": Choose device

":EditDeviceUI" -> ":EditDeviceCTRL": removeDevice(roomIndex, deviceIndex)

":EditDeviceCTRL" -> ":Room": removeDevice(roomIndex, deviceIndex)
deactivate ":EditDeviceCTRL"
":Room" -> "dL :DeviceList": removeDevice(deviceIndex)

@enduml