@startuml
autonumber
hidefootbox
actor PowerUser

activate PowerUser
PowerUser -> ":EnergyConsumptionInPeriodUI": Get Total Metered\nEnergy Consumption
activate  ":EnergyConsumptionInPeriodUI"
PowerUser <-- ":EnergyConsumptionInPeriodUI": Show Options: Device,Room,Grid
PowerUser -> ":EnergyConsumptionInPeriodUI": Choose Room option
":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": rL=showRoomListInStr()
activate ":EnergyConsumptionInPeriodCTRL"
":EnergyConsumptionInPeriodCTRL" -> "rL:RoomList": rL=showRoomListInStr()
activate "rL:RoomList"
deactivate "rL:RoomList"
PowerUser <-- ":EnergyConsumptionInPeriodUI": Show Room list
PowerUser -> ":EnergyConsumptionInPeriodUI": Choose a Room
PowerUser <-- ":EnergyConsumptionInPeriodUI": Ask for the time interval
PowerUser -> ":EnergyConsumptionInPeriodUI": Input the time interval
":EnergyConsumptionInPeriodUI" -> ":EnergyConsumptionInPeriodCTRL": tMe=getEnergyConsumption\nInPeriod(index, start, end)
":EnergyConsumptionInPeriodCTRL" -> ":Room": tMe=getEnergyConsumption\nInPeriod(index, start, end)
activate ":Room"
":Room" -> ":Device": tMe = getEnergyConsumption\nInPeriod(start, end)
activate ":Device"
":Device" -> "i:ReadConfigFile": i:getDevicesMeteringPeriod()
activate "i:ReadConfigFile"
deactivate "i:ReadConfigFile"
":Device" -> ":ReadingList": tMe=getValueOfReadings\nInTimeInterval(start, end)
activate ":ReadingList"
":ReadingList" -> "r:Reading": r=returnValueOfReading
activate "r:Reading"
deactivate "r:Reading"
deactivate ":ReadingList"
deactivate ":Device"
PowerUser <-- ":EnergyConsumptionInPeriodUI": Show Total Metered Energy\nConsumption in the Room
deactivate ":Room"
deactivate ":EnergyConsumptionInPeriodCTRL"
deactivate ":EnergyConsumptionInPeriodUI"


@enduml
