@startuml
title Total Nominal Power In a Grid
hidefootbox
actor User

User -> ":GetTotalNominalPowerUI": Show Total Nominal\nPower of a Grid
create ":GetTotalNominalPowerCTRL"
":GetTotalNominalPowerUI" -> ":GetTotalNominalPowerCTRL": getGridTotalNominalPower()

":GetTotalNominalPowerUI" -> ":GetTotalNominalPowerCTRL": gE=checkIfGridListEmpty()
":GetTotalNominalPowerCTRL" -> ":HouseGridList": gE=getGridListSize()

":GetTotalNominalPowerUI" -> ":GetTotalNominalPowerCTRL": rE=checkIfRoomListEmpty()
":GetTotalNominalPowerCTRL" -> ":RoomList": rE=getRoomListSize()

":GetTotalNominalPowerUI" -> ":GetTotalNominalPowerCTRL": gLs=selectGrid()
":GetTotalNominalPowerCTRL" -> ":HouseGridList": gLs=showGridListInString()
":GetTotalNominalPowerUI" --> User: gLs=showGridList
User -> ":GetTotalNominalPowerUI": Choose Grid

":GetTotalNominalPowerUI" -> ":GetTotalNominalPowerCTRL": rG=checkIfRoomsExistsInGrid()
":GetTotalNominalPowerCTRL" -> ":HouseGrid": rG=getSizeRoomListInGrid(indexGrid)

":GetTotalNominalPowerUI" -> ":GetTotalNominalPowerCTRL": dL=checkIfDevicesExistsInGrid()
":GetTotalNominalPowerCTRL" -> ":HouseGrid": dL=getSizeDeviceListInGrid(indexGrid)

":GetTotalNominalPowerCTRL" -> ":HouseGrid": nP=getGridTotalNominalPower(indexGrid)
loop room sum
    ":HouseGrid" -> ":Room": nP=getNominalPower
   end

 loop device sum
    ":Room" -> ":Device": nP=getNominalPower
   end
":GetTotalNominalPowerUI" -->User: nP: Show Total Nominal\nPower of a Grid



@enduml