@startuml

skinparam sequence {
	ArrowColor SteelBlue
	ActorBorderColor Dimgray
	LifeLineBorderColor MidnightBlue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Dimgray
	ParticipantBackgroundColor SteelBlue
	ParticipantFontName Calibri Bold
	ParticipantFontSize 17
	ParticipantFontColor Ivory

	ActorBackgroundColor SteelBlue
	ActorFontColor MidnightBlue
	ActorFontSize 17
	ActorFontName Aapex
}

skinparam note {
BorderColor SteelBlue
}

"End User \n Application" -> ":GeoAreaCTRL": GET request \n/geoareas/getParent

":GeoAreaCTRL" -> ":GeoAreaService" : showListOfGAS()

":GeoAreaService" -> ":GeoRepository" : findById(idHG)

":GeoAreaCTRL" -> ":GeoAreaService" : searchRoomsbyHG(idHG)

":GeoAreaService" -> ":GeoRepository" : List<GeographicalArea> = findbyHGid(idHG)

loop  Conversion of List<Room> to List<RoomDTO>
":GeoAreaService" -> "ModelMapper": RoomDTO = model.map(Room,RoomDTO.class)
end
":GeoAreaService" --> ":GeoAreaCTRL" : resultdto

":GeoAreaCTRL" --> "End User \n Application" : Response status \nand result message
@enduml