@startuml

skinparam sequence {
	ArrowColor SteelBlue
	ActorBorderColor Dimgray
	LifeLineBorderColor MidnightBlue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor Dimgray
	ParticipantBackgroundColor SteelBlue
	ParticipantFontName Calibri Bold
	ParticipantFontSize 17
	ParticipantFontColor Ivory

	ActorBackgroundColor SteelBlue
	ActorFontColor MidnightBlue
	ActorFontSize 17
	ActorFontName Aapex
}

skinparam note {
BorderColor SteelBlue
}

"HTTP Client" -> ":HouseGridCTRL": GET \n/housegrids/{id}/rooms

create ":HouseGridService"
":HouseGridCTRL" -> ":HouseGridService" : create( )
":HouseGridCTRL" -> ":HouseGridService" : gridExists(id)

":HouseGridService" -> ":HouseGridRepository" : existsbyId(id)

create "responseEntity \n:ResponseEntity"
":HouseGridCTRL" ->  "responseEntity \n:ResponseEntity": responseEntity = new ResponseEntity<>(message, HttpStatus.NOT_FOUND);

":HouseGridCTRL" --> "HTTP Client" : Status.NOT_FOUND \nResponse message
@enduml